[package]
name = "day_11"
version = "0.1.0"
authors = ["James Lomax <james.lomax@cambridgeconsultants.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { version = "^0", path = "../common" }
